name: UpdateCSV

on:
  push:
    branches: [cachehack]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout emergenzeHack/covid19italia
      uses: actions/checkout@v2
      with:
        repository: emergenzeHack/covid19italia

    - name: Get data repository name
      run: |
        echo "::set-output name=repo::covid19italia_data"
      id: get_data_repo

    - name: Checkout ${{steps.get_data_repo.outputs.repo }}
      uses: actions/checkout@v2
      with:
        repository: ${{steps.get_data_repo.outputs.repo }}
        path: _data/machgen

    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-2.6.x-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-2.6.x-gems-

    - name: Cache pips
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-3.x-pip

    - uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.x

    - name: Install packages with pip
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        pip install lxml PyGithub pyyaml shapely pandas geopandas

    - name: Recreate CSV, JSON and GeoJSON and push them
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      working-directory:
        _data/machgen
      run: |
        mkdir -m 700 ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
        git fetch origin
        git reset --hard origin/master
        ../../scripts/github2CSV.py issues.csv issuesjson.json issues.geojson ../../_utilities ${{ secrets.ACCEPTED_LABEL }}
        wc -l issues.csv
        wc -l issuesjson.json
